name: Go
on:
  push:
    branches:
      - "master"

jobs:
  release-please:
    name: Run release-please
    runs-on: ubuntu-latest
    if: github.repository == 'jtwatson/shutdown'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
