name: Go
on:
  push:
    branches:
      - "master"

jobs:
  semantic-release:
    name: Run semantic-release
    runs-on: ubuntu-latest
    if: |
      github.repository == 'jtwatson/shutdown' &&
      github.event.pull_request.merged
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install and run semantic-release
        run: |
          npm install --save-dev semantic-release@19
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
